# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/UCT 2023/EEE4120F High Performance Embedded Systems/Practicals/Prac 3/project_1/project_1.srcs/sources_1/ip/bram_Sine_LUT/bram_Sine_LUT.xci
# IP: The module: 'bram_Sine_LUT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UCT 2023/EEE4120F High Performance Embedded Systems/Practicals/Prac 3/project_1/project_1.srcs/sources_1/ip/bram_Sine_LUT/bram_Sine_LUT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_Sine_LUT'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/UCT 2023/EEE4120F High Performance Embedded Systems/Practicals/Prac 3/project_1/project_1.srcs/sources_1/ip/bram_Sine_LUT/bram_Sine_LUT.xci
# IP: The module: 'bram_Sine_LUT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UCT 2023/EEE4120F High Performance Embedded Systems/Practicals/Prac 3/project_1/project_1.srcs/sources_1/ip/bram_Sine_LUT/bram_Sine_LUT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_Sine_LUT'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
